// <auto-generated />
using System;
using Examen_ASP_NET.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen_ASP_NET.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240813083853_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Examen_ASP_NET.Domain.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnswerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResultId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Question", b =>
                {
                    b.HasOne("Examen_ASP_NET.Domain.Answer", null)
                        .WithMany("Question")
                        .HasForeignKey("AnswerId");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Test", b =>
                {
                    b.HasOne("Examen_ASP_NET.Domain.Question", null)
                        .WithMany("Test")
                        .HasForeignKey("QuestionId");

                    b.HasOne("Examen_ASP_NET.Domain.Result", null)
                        .WithMany("Test")
                        .HasForeignKey("ResultId");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.User", b =>
                {
                    b.HasOne("Examen_ASP_NET.Domain.Result", null)
                        .WithMany("User")
                        .HasForeignKey("ResultId");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Answer", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Question", b =>
                {
                    b.Navigation("Test");
                });

            modelBuilder.Entity("Examen_ASP_NET.Domain.Result", b =>
                {
                    b.Navigation("Test");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
